"""add custom_domain

Revision ID: 5e3932043eaa
Revises: 56f5584c231f
Create Date: 2026-03-17 17:58:49.853338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3932043eaa'
down_revision = '56f5584c231f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_domain', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['custom_domain'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('custom_domain')

    # ### end Alembic commands ###
